name: doc_scanner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.1

dependencies:
  archive: ^4.0.9
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  get: ^4.7.2
  image_picker: ^1.2.2
  open_filex: ^4.7.0
  path_provider: ^2.1.6
  syncfusion_flutter_pdf: ^33.2.13
  syncfusion_flutter_pdfviewer: ^33.2.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tessdata/khm.traineddata
    - assets/tessdata/eng.traineddata
